# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: value_sets.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='value_sets.proto',
  package='app.coronawarn.server.common.protocols.internal.dgc',
  syntax='proto3',
  serialized_options=b'P\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10value_sets.proto\x12\x33\x61pp.coronawarn.server.common.protocols.internal.dgc\"\x9e\x04\n\tValueSets\x12I\n\x02tg\x18\x04 \x01(\x0b\x32=.app.coronawarn.server.common.protocols.internal.dgc.ValueSet\x12I\n\x02vp\x18\x01 \x01(\x0b\x32=.app.coronawarn.server.common.protocols.internal.dgc.ValueSet\x12I\n\x02mp\x18\x02 \x01(\x0b\x32=.app.coronawarn.server.common.protocols.internal.dgc.ValueSet\x12I\n\x02ma\x18\x03 \x01(\x0b\x32=.app.coronawarn.server.common.protocols.internal.dgc.ValueSet\x12K\n\x04tcTt\x18\x05 \x01(\x0b\x32=.app.coronawarn.server.common.protocols.internal.dgc.ValueSet\x12K\n\x04tcMa\x18\x06 \x01(\x0b\x32=.app.coronawarn.server.common.protocols.internal.dgc.ValueSet\x12K\n\x04tcTr\x18\x07 \x01(\x0b\x32=.app.coronawarn.server.common.protocols.internal.dgc.ValueSet\"\\\n\x08ValueSet\x12P\n\x05items\x18\x01 \x03(\x0b\x32\x41.app.coronawarn.server.common.protocols.internal.dgc.ValueSetItem\"0\n\x0cValueSetItem\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x13\n\x0b\x64isplayText\x18\x02 \x01(\tB\x02P\x01\x62\x06proto3'
)




_VALUESETS = _descriptor.Descriptor(
  name='ValueSets',
  full_name='app.coronawarn.server.common.protocols.internal.dgc.ValueSets',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='tg', full_name='app.coronawarn.server.common.protocols.internal.dgc.ValueSets.tg', index=0,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vp', full_name='app.coronawarn.server.common.protocols.internal.dgc.ValueSets.vp', index=1,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mp', full_name='app.coronawarn.server.common.protocols.internal.dgc.ValueSets.mp', index=2,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ma', full_name='app.coronawarn.server.common.protocols.internal.dgc.ValueSets.ma', index=3,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tcTt', full_name='app.coronawarn.server.common.protocols.internal.dgc.ValueSets.tcTt', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tcMa', full_name='app.coronawarn.server.common.protocols.internal.dgc.ValueSets.tcMa', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tcTr', full_name='app.coronawarn.server.common.protocols.internal.dgc.ValueSets.tcTr', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=74,
  serialized_end=616,
)


_VALUESET = _descriptor.Descriptor(
  name='ValueSet',
  full_name='app.coronawarn.server.common.protocols.internal.dgc.ValueSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='app.coronawarn.server.common.protocols.internal.dgc.ValueSet.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=618,
  serialized_end=710,
)


_VALUESETITEM = _descriptor.Descriptor(
  name='ValueSetItem',
  full_name='app.coronawarn.server.common.protocols.internal.dgc.ValueSetItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='app.coronawarn.server.common.protocols.internal.dgc.ValueSetItem.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='displayText', full_name='app.coronawarn.server.common.protocols.internal.dgc.ValueSetItem.displayText', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=712,
  serialized_end=760,
)

_VALUESETS.fields_by_name['tg'].message_type = _VALUESET
_VALUESETS.fields_by_name['vp'].message_type = _VALUESET
_VALUESETS.fields_by_name['mp'].message_type = _VALUESET
_VALUESETS.fields_by_name['ma'].message_type = _VALUESET
_VALUESETS.fields_by_name['tcTt'].message_type = _VALUESET
_VALUESETS.fields_by_name['tcMa'].message_type = _VALUESET
_VALUESETS.fields_by_name['tcTr'].message_type = _VALUESET
_VALUESET.fields_by_name['items'].message_type = _VALUESETITEM
DESCRIPTOR.message_types_by_name['ValueSets'] = _VALUESETS
DESCRIPTOR.message_types_by_name['ValueSet'] = _VALUESET
DESCRIPTOR.message_types_by_name['ValueSetItem'] = _VALUESETITEM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ValueSets = _reflection.GeneratedProtocolMessageType('ValueSets', (_message.Message,), {
  'DESCRIPTOR' : _VALUESETS,
  '__module__' : 'value_sets_pb2'
  # @@protoc_insertion_point(class_scope:app.coronawarn.server.common.protocols.internal.dgc.ValueSets)
  })
_sym_db.RegisterMessage(ValueSets)

ValueSet = _reflection.GeneratedProtocolMessageType('ValueSet', (_message.Message,), {
  'DESCRIPTOR' : _VALUESET,
  '__module__' : 'value_sets_pb2'
  # @@protoc_insertion_point(class_scope:app.coronawarn.server.common.protocols.internal.dgc.ValueSet)
  })
_sym_db.RegisterMessage(ValueSet)

ValueSetItem = _reflection.GeneratedProtocolMessageType('ValueSetItem', (_message.Message,), {
  'DESCRIPTOR' : _VALUESETITEM,
  '__module__' : 'value_sets_pb2'
  # @@protoc_insertion_point(class_scope:app.coronawarn.server.common.protocols.internal.dgc.ValueSetItem)
  })
_sym_db.RegisterMessage(ValueSetItem)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
